#!/usr/bin/env bash
# setup_autostart.sh
# Creates ~/.config/autostart/easymoney-dashboard.desktop so that
# run_pi_playwright_login.sh launches automatically on desktop login (LXDE / LightDM / etc.)
set -euo pipefail

# ── paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIN_SCRIPT="$SCRIPT_DIR/run_pi_playwright_login.sh"

AUTOSTART_DIR="$HOME/.config/autostart"
DESKTOP_FILE="$AUTOSTART_DIR/easymoney-dashboard.desktop"

# Wrapper script that sources the env file and then calls the main script.
# Keeping it separate makes it easy to edit env vars without touching autostart.
WRAPPER_SCRIPT="$SCRIPT_DIR/autostart_wrapper.sh"
ENV_FILE="$SCRIPT_DIR/.env.autostart"

# ── optional: startup delay (seconds) so the desktop is fully ready ───────────
STARTUP_DELAY="${STARTUP_DELAY:-8}"

# ─────────────────────────────────────────────────────────────────────────────
log() { echo "[setup_autostart] $*"; }

# 1. Verify the main script exists
if [[ ! -f "$MAIN_SCRIPT" ]]; then
  echo "ERROR: run_pi_playwright_login.sh not found at: $MAIN_SCRIPT"
  exit 1
fi
chmod +x "$MAIN_SCRIPT"

# 2. Create env file (only if it doesn't exist, so credentials aren't overwritten)
if [[ ! -f "$ENV_FILE" ]]; then
  log "Creating env file: $ENV_FILE"
  cat > "$ENV_FILE" <<'EOF'
# Environment variables for easymoney-dashboard autostart.
# Edit this file to set your credentials and any overrides.
# Lines starting with # are comments.

# Required: login credentials
LOGIN_USER=""
LOGIN_PASS=""

# Optional overrides (leave empty to use defaults in run_pi_playwright_login.sh)
# URL="https://www.hyxicloud.com"
# REDIRECT_URL="https://www.hyxicloud.com/#/dataWall"
# FULLSCREEN_MODE="kiosk"        # kiosk | maximized
# HEADLESS=0                     # 0=headful, 1=headless
# WAIT_AFTER_LOGIN_SECONDS=5
# TAB_SWITCH=true
# TAB_SWITCH_INTERVAL=300
# EXTRA_TAB_URLS=""              # space-separated extra URLs
# CHROMIUM_PATH=""               # override chromium binary path
# WORKDIR=""                     # override working directory
EOF
  log "  -> Edit $ENV_FILE to add your LOGIN_USER / LOGIN_PASS."
else
  log "Env file already exists, skipping: $ENV_FILE"
fi

# 3. Create wrapper script
log "Writing wrapper script: $WRAPPER_SCRIPT"
cat > "$WRAPPER_SCRIPT" <<EOF
#!/usr/bin/env bash
# autostart_wrapper.sh  –  generated by setup_autostart.sh
# Sources the env file then launches run_pi_playwright_login.sh

ENV_FILE="\${ENV_FILE:-$ENV_FILE}"
MAIN_SCRIPT="$MAIN_SCRIPT"
STARTUP_DELAY="$STARTUP_DELAY"

# Give the desktop environment time to finish loading
sleep "\$STARTUP_DELAY"

# Source env vars if the file exists and is non-empty
if [[ -f "\$ENV_FILE" ]]; then
  # Export only non-comment, non-blank lines
  set -o allexport
  # shellcheck disable=SC1090
  source <(grep -v '^\s*#' "\$ENV_FILE" | grep -v '^\s*$')
  set +o allexport
fi

exec "\$MAIN_SCRIPT"
EOF
chmod +x "$WRAPPER_SCRIPT"

# 4. Create the autostart directory and .desktop file
mkdir -p "$AUTOSTART_DIR"

log "Writing desktop entry: $DESKTOP_FILE"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=EasyMoney Dashboard
Comment=Auto-launch Playwright login for EasyMoney Dashboard
Exec=$WRAPPER_SCRIPT
Terminal=false
Hidden=false
X-GNOME-Autostart-enabled=true
X-LXSession-Smproxy=false
EOF

# 5. Summary
echo ""
echo "========================================"
echo " Autostart setup complete"
echo "========================================"
echo " Desktop entry : $DESKTOP_FILE"
echo " Wrapper script: $WRAPPER_SCRIPT"
echo " Env file      : $ENV_FILE"
echo " Startup delay : ${STARTUP_DELAY}s"
echo ""
echo " Next steps:"
echo "   1. Edit $ENV_FILE"
echo "      and fill in LOGIN_USER and LOGIN_PASS."
echo "   2. (Optional) Adjust STARTUP_DELAY by re-running:"
echo "        STARTUP_DELAY=10 bash setup_autostart.sh"
echo "   3. Reboot (or log out and back in) to test autostart."
echo "      To test immediately without rebooting:"
echo "        bash $WRAPPER_SCRIPT"
echo "========================================"
