#!/usr/bin/env bash
# setup_autostart.sh
# Creates ~/.config/autostart/easymoney-dashboard.desktop so that
# run_pi_playwright_login.sh launches automatically on desktop login (LXDE / LightDM / etc.)
set -euo pipefail

# ── paths ─────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIN_SCRIPT="$SCRIPT_DIR/run_pi_playwright_login.sh"

AUTOSTART_DIR="$HOME/.config/autostart"
DESKTOP_FILE="$AUTOSTART_DIR/easymoney-dashboard.desktop"

# Wrapper script that calls the main script (credentials come from .env in SCRIPT_DIR)
WRAPPER_SCRIPT="$SCRIPT_DIR/autostart_wrapper.sh"

# ── optional: startup delay (seconds) so the desktop is fully ready ───────────
STARTUP_DELAY="${STARTUP_DELAY:-8}"

# ─────────────────────────────────────────────────────────────────────────────
log() { echo "[setup_autostart] $*"; }

# 1. Verify the main script exists
if [[ ! -f "$MAIN_SCRIPT" ]]; then
  echo "ERROR: run_pi_playwright_login.sh not found at: $MAIN_SCRIPT"
  exit 1
fi
chmod +x "$MAIN_SCRIPT"

# 2. Create wrapper script
log "Writing wrapper script: $WRAPPER_SCRIPT"

cat > "$WRAPPER_SCRIPT" <<EOF
#!/usr/bin/env bash
# autostart_wrapper.sh  –  generated by setup_autostart.sh
# Waits for the desktop to be ready, then launches run_pi_playwright_login.sh.
# Credentials are read from .env inside the project directory by the main script.

STARTUP_DELAY="$STARTUP_DELAY"

# Give the desktop environment time to finish loading
sleep "\$STARTUP_DELAY"

exec "$MAIN_SCRIPT"
EOF
chmod +x "$WRAPPER_SCRIPT"

# 3. Create the autostart directory and .desktop file
mkdir -p "$AUTOSTART_DIR"

log "Writing desktop entry: $DESKTOP_FILE"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=EasyMoney Dashboard
Comment=Auto-launch Playwright login for EasyMoney Dashboard
Exec=$WRAPPER_SCRIPT
Terminal=false
Hidden=false
X-GNOME-Autostart-enabled=true
X-LXSession-Smproxy=false
EOF

# 4. Summary
echo ""
echo "========================================"
echo " Autostart setup complete"
echo "========================================"
echo " Desktop entry : $DESKTOP_FILE"
echo " Wrapper script: $WRAPPER_SCRIPT"
echo " Credentials   : read from $SCRIPT_DIR/.env"
echo " Startup delay : ${STARTUP_DELAY}s"
echo ""
echo " Next steps:"
echo "   1. Make sure $SCRIPT_DIR/.env contains LOGIN_USER and LOGIN_PASS."
echo "   2. (Optional) Adjust STARTUP_DELAY by re-running:"
echo "        STARTUP_DELAY=10 bash setup_autostart.sh"
echo "   3. Reboot (or log out and back in) to test autostart."
echo "      To test immediately without rebooting:"
echo "        bash $WRAPPER_SCRIPT"
echo "========================================"
